"""adicionar indices de performance em pedidos e produtos

Revision ID: 64609e0943d9
Revises: 7507a7e604df
Create Date: 2026-07-27 19:26:07.083375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '64609e0943d9'
down_revision: Union[str, None] = '7507a7e604df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pedidos_criado_em'), 'pedidos', ['criado_em'], unique=False)
    op.create_index(op.f('ix_pedidos_status'), 'pedidos', ['status'], unique=False)
    op.create_index(op.f('ix_pedidos_usuario_id'), 'pedidos', ['usuario_id'], unique=False)
    op.create_index(op.f('ix_produtos_ativo'), 'produtos', ['ativo'], unique=False)
    op.create_index(op.f('ix_produtos_categoria_id'), 'produtos', ['categoria_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_categoria_id'), table_name='produtos')
    op.drop_index(op.f('ix_produtos_ativo'), table_name='produtos')
    op.drop_index(op.f('ix_pedidos_usuario_id'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_status'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_criado_em'), table_name='pedidos')
    # ### end Alembic commands ###
