"""adicionar usuario_tokens e email_verificado

Revision ID: 7507a7e604df
Revises: efba00986d13
Create Date: 2026-07-27 11:57:11.962778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7507a7e604df'
down_revision: Union[str, None] = 'efba00986d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', postgresql.ENUM('verificacao_email', 'redefinicao_senha', name='tipo_token_usuario_enum'), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_tokens_token'), 'usuario_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_usuario_tokens_usuario_id'), 'usuario_tokens', ['usuario_id'], unique=False)
    op.add_column('usuarios', sa.Column('email_verificado', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'email_verificado')
    op.drop_index(op.f('ix_usuario_tokens_usuario_id'), table_name='usuario_tokens')
    op.drop_index(op.f('ix_usuario_tokens_token'), table_name='usuario_tokens')
    op.drop_table('usuario_tokens')
    # ### end Alembic commands ###
